"""add_sponsored_universities_to_users

Revision ID: c7bb95785938
Revises: 395d178364ac
Create Date: 2026-03-01 14:17:22.451368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bb95785938'
down_revision: Union[str, Sequence[str], None] = '395d178364ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sponsored_universities', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sponsored_universities')
    # ### end Alembic commands ###
